### ISSUE TITLE
libavcodec.so.57: Cannot open shared object file

### ISSUE THREAD

**Issue by hkpc0715** [DaWelter/h264decoder#3]
Hi all,

I was trying out both Tello_Video & Tello_Video_With_Pose_Recognition packages in my Linux - ubuntu 16.04 LTS

At first, I installed Tello_Video with the one click install and it has successfully run, however, when i tries to install and run Tello_VIdeo_With_Pose_Recognition, it shows the following errors, and now it no longer runs again.

I have checked and I moved the 'libh264decoder.so' file into my python's site-packages file & /usr/lib/ , the above move was suggested by the internet. But still getting the error:

`spark@spark:~/Downloads/Tello-Python-master/Tello_Video_With_Pose_Recognition$ python main.py`

Traceback (most recent call last):
File "main.py", line 1, in
import tello
File "/home/spark/Downloads/Tello-Python-master/Tello_Video_With_Pose_Recognition/tello.py", line 5, in
import libh264decoder
ImportError: libavcodec.so.57: cannot open shared object file: No such file or directory
`
spark@spark:~/Downloads/Tello-Python-master/Tello_Video_With_Pose_Recognition$ cd ..`
`spark@spark:~/Downloads/Tello-Python-master$ cd Tello_Video`

`spark@spark:~/Downloads/Tello-Python-master/Tello_Video$ python main.py
`
Traceback (most recent call last):
File "main.py", line 1, in
import tello
File "/home/spark/Downloads/Tello-Python-master/Tello_Video/tello.py", line 5, in
import libh264decoder
ImportError: libavcodec.so.57: cannot open shared object file: No such file or directory
spark@spark:~/Downloads/Tello-Python-master/Tello_Video$ `

Any help will be greatly appreciated.

**Comment by petri** [comment]
You are missing some of the libavcodec ubuntu packages, or, if you have the right packages, Python is not able to find the shared libavcodec libraries. Check what you have, and google how to install needed packages & how to resolve any path issues. Sorry, cannot help you more than that.
